$ANSIBLE_VAULT;1.1;AES256
31323238663866336139663666323665363930343738353964373964306562646365623733323962
3930663633326664616634376263613966313534666466300a363763333137636536383066313230
66376561373536366630323463323266366430363332663237653333363565626234346138313261
3936616435616166610a396565386639313935373331383737376331316137633638393135646336
35396631623565343333336339346362666361656236386562376561633061616663343238336163
38666137303563663432393166386338306433363831613865663234396234333361396161363330
37653735393430303466383666646264376636646562623964653230663833646666353231383131
63333736653662623665356534353466333231343761306162656462353634633232633138386133
30393037373266393838653637643130353238336532313763653164303335613465
